# Generated by Django 5.0.7 on 2025-06-10 11:26

from django.db import migrations


def fix_user_roles(apps, schema_editor):
    """Convert all user roles to lowercase to match model choices"""
    User = apps.get_model('accounts', 'User')
    
    # Map uppercase roles to lowercase
    role_mapping = {
        'DEVELOPER': 'developer',
        'OWNER': 'owner', 
        'SALESMAN': 'salesman',
        'SHOP': 'shop',
    }
    
    for old_role, new_role in role_mapping.items():
        User.objects.filter(role=old_role).update(role=new_role)
    
    print(f"Fixed user roles: {role_mapping}")


def reverse_fix_user_roles(apps, schema_editor):
    """Reverse the role fixes (convert back to uppercase)"""
    User = apps.get_model('accounts', 'User')
    
    # Map lowercase roles back to uppercase
    role_mapping = {
        'developer': 'DEVELOPER',
        'owner': 'OWNER',
        'salesman': 'SALESMAN', 
        'shop': 'SHOP',
    }
    
    for old_role, new_role in role_mapping.items():
        User.objects.filter(role=old_role).update(role=new_role)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_user_roles, reverse_fix_user_roles),
    ]
