# Generated by Django 5.0.7 on 2025-07-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('labour', 'Labour'), ('accommodation', 'Accommodation'), ('other', 'Other')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ref_id', models.CharField(blank=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'delivery_expenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='deliverysettlementitem',
            name='delivery_se_settlem_fe09c3_idx',
        ),
        migrations.AlterUniqueTogether(
            name='deliverysettlement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='deliverysettlementitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='deliverysettlementitem',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settlement_items', to='products.delivery'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverysettlementitem',
            unique_together={('settlement', 'product', 'delivery')},
        ),
        migrations.AddIndex(
            model_name='deliverysettlementitem',
            index=models.Index(fields=['settlement', 'product', 'delivery'], name='delivery_se_settlem_7eb0f5_idx'),
        ),
        migrations.AddField(
            model_name='deliveryexpense',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='products.delivery'),
        ),
    ]
