# Generated by Django 5.0.7 on 2025-06-18 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delivery_deliveryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.CreateModel(
            name='CentralStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('owner', 'Owner Stock'), ('salesman', 'Salesman Stock')], max_length=20)),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_locations', to='products.product')),
            ],
            options={
                'db_table': 'central_stock',
                'indexes': [models.Index(fields=['product', 'location_type'], name='central_sto_product_10d826_idx'), models.Index(fields=['location_type', 'location_id'], name='central_sto_locatio_218baa_idx')],
                'unique_together': {('product', 'location_type', 'location_id')},
            },
        ),
    ]
