# Generated by Django 4.x on 2025-07-06 for batch-based stock management refactor

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_central_stock_system'),
    ]

    operations = [
        # Drop the CentralStock table
        migrations.RunSQL(
            "DROP TABLE IF EXISTS central_stock CASCADE;",
            reverse_sql="-- Cannot reverse: Table dropped"
        ),
        
        # Drop the SalesmanStock table (legacy)
        migrations.RunSQL(
            "DROP TABLE IF EXISTS salesman_stock CASCADE;",
            reverse_sql="-- Cannot reverse: Table dropped"
        ),
        
        # Add delivery reference to batch assignments if not exists
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN 
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'batch_assignments' 
                    AND column_name = 'delivery_id'
                ) THEN
                    ALTER TABLE batch_assignments 
                    ADD COLUMN delivery_id INTEGER REFERENCES deliveries(id) ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE batch_assignments DROP COLUMN IF EXISTS delivery_id;"
        ),
    ]
