# Generated by Django 5.0.7 on 2025-06-21 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_user_roles'),
        ('products', '0004_add_central_stock_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        
       
      
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('settled', 'Settled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='User-defined batch number', max_length=100)),
                ('manufacturing_date', models.DateField(help_text='Manufacturing or received date')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiry date for FIFO', null=True)),
                ('initial_quantity', models.PositiveIntegerField(help_text='Initial quantity in this batch')),
                ('current_quantity', models.PositiveIntegerField(help_text='Current available quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost per unit for this batch', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this batch', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
            ],
            options={
                'db_table': 'product_batches',
                'ordering': ['manufacturing_date', 'expiry_date'],
                'unique_together': {('product', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='BatchAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity assigned')),
                ('delivered_quantity', models.PositiveIntegerField(default=0, help_text='Quantity actually delivered')),
                ('returned_quantity', models.PositiveIntegerField(default=0, help_text='Quantity returned')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('partial', 'Partially Returned'), ('returned', 'Fully Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='products.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='accounts.salesman')),
            ],
            options={
                'db_table': 'batch_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('restock', 'Restock'), ('assignment', 'Assignment to Salesman'), ('sale', 'Sale'), ('return', 'Return from Salesman'), ('adjustment', 'Stock Adjustment'), ('expired', 'Expired Stock Removal')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('balance_after', models.PositiveIntegerField(help_text='Stock balance after this transaction')),
                ('reference_type', models.CharField(blank=True, help_text='Type of reference (delivery, invoice, etc.)', max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of related record', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='products.batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
