# Generated by Django 5.0.7 on 2025-06-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_batch_management_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='settlement_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total_margin_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
