# Generated by Django 5.0.7 on 2025-07-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_central_stock_system'),
        ('products', '0006_delivery_settlement_date_delivery_settlement_notes_and_more'),
    ]

    operations = [
    ]
