# Generated by Django 5.0.7 on 2025-07-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20250706_1511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesmanstock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='salesmanstock',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesmanstock',
            name='salesman',
        ),
        migrations.AddField(
            model_name='batchassignment',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_assignments', to='products.delivery'),
        ),
        migrations.DeleteModel(
            name='CentralStock',
        ),
        migrations.DeleteModel(
            name='SalesmanStock',
        ),
    ]
