# Generated by Django 5.0.7 on 2025-07-06 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_salesmanstock_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='quality_status',
            field=models.CharField(choices=[('GOOD', 'Good Quality'), ('WARNING', 'Quality Warning'), ('DEFECTIVE', 'Defective'), ('RECALLED', 'Recalled')], default='GOOD', help_text='Quality status of the batch', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='recall_initiated_at',
            field=models.DateTimeField(blank=True, help_text='When recall was initiated', null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='recall_reason',
            field=models.TextField(blank=True, help_text='Reason for batch recall'),
        ),
        migrations.AddField(
            model_name='batch',
            name='return_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Return rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='batch',
            name='total_returned',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total quantity returned', max_digits=10),
        ),
        migrations.CreateModel(
            name='BatchDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_type', models.CharField(choices=[('QUALITY', 'Quality Issue'), ('CONTAMINATION', 'Contamination'), ('EXPIRY', 'Premature Expiry'), ('PACKAGING', 'Packaging Defect'), ('OTHER', 'Other Issue')], max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical - Immediate Recall')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the defect')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the defect was resolved')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='products.batch')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_defects', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_defects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'batch_defects',
                'ordering': ['-reported_at'],
            },
        ),
    ]
