# Generated by Django 5.0.7 on 2025-07-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_user_roles'),
        ('products', '0009_batch_quality_status_batch_recall_initiated_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchassignment',
            unique_together={('batch', 'delivery', 'salesman')},
        ),
    ]
