# Generated by Django 5.0.7 on 2025-07-07 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_user_roles'),
        ('products', '0010_fix_batch_assignment_duplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_date', models.DateField()),
                ('settlement_number', models.CharField(max_length=50, unique=True)),
                ('total_delivered_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_sold_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_returned_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_margin_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_delivered_items', models.PositiveIntegerField(default=0)),
                ('total_sold_items', models.PositiveIntegerField(default=0)),
                ('total_returned_items', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('settlement_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_settlements', to='accounts.salesman')),
                ('settled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'delivery_settlements',
                'ordering': ['-settlement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliverySettlementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.PositiveIntegerField()),
                ('sold_quantity', models.PositiveIntegerField(default=0)),
                ('returned_quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivered_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('returned_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('margin_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_margin_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.deliverysettlement')),
            ],
            options={
                'db_table': 'delivery_settlement_items',
            },
        ),
        migrations.AddIndex(
            model_name='deliverysettlement',
            index=models.Index(fields=['salesman', 'settlement_date'], name='delivery_se_salesma_d43bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverysettlement',
            index=models.Index(fields=['settlement_date'], name='delivery_se_settlem_170c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverysettlement',
            index=models.Index(fields=['status'], name='delivery_se_status_666b53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverysettlement',
            unique_together={('salesman', 'settlement_date')},
        ),
        migrations.AddIndex(
            model_name='deliverysettlementitem',
            index=models.Index(fields=['settlement', 'product'], name='delivery_se_settlem_fe09c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverysettlementitem',
            unique_together={('settlement', 'product')},
        ),
    ]
