# Generated by Django 5.0.7 on 2025-07-11 09:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('income', 'Additional Income'), ('expense', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Categories',
                'db_table': 'finance_transaction_categories',
                'ordering': ['transaction_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProfitSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_invoices', models.IntegerField(default=0)),
                ('settled_invoices', models.IntegerField(default=0)),
                ('unsettled_invoices', models.IntegerField(default=0)),
                ('invoice_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unsettled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_of_goods_settled', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_of_goods_unsettled', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_pending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('realized_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unrealized_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spendable_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_efficiency', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_profit_summaries',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['period_type', 'start_date'], name='finance_pro_period__1e7d99_idx'), models.Index(fields=['start_date', 'end_date'], name='finance_pro_start_d_981f89_idx')],
                'unique_together': {('period_type', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_basis', models.CharField(choices=[('total_sales', 'Total Sales'), ('profit_margin', 'Profit Margin'), ('cash_collected', 'Cash Collected')], default='cash_collected', max_length=20)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='calculated', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='sales.invoice')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='accounts.salesman')),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='sales.invoicesettlement')),
            ],
            options={
                'db_table': 'finance_commission_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invoice'], name='finance_com_invoice_cd8838_idx'), models.Index(fields=['salesman'], name='finance_com_salesma_fea4a5_idx'), models.Index(fields=['status'], name='finance_com_status_2723e5_idx'), models.Index(fields=['payment_date'], name='finance_com_payment_d43c65_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='finance/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.transactioncategory')),
            ],
            options={
                'db_table': 'finance_transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_date'], name='finance_tra_transac_bb542a_idx'), models.Index(fields=['category'], name='finance_tra_categor_824f43_idx'), models.Index(fields=['created_by'], name='finance_tra_created_695814_idx')],
            },
        ),
        migrations.CreateModel(
            name='DescriptionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, unique=True)),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='finance.transactioncategory')),
            ],
            options={
                'db_table': 'finance_description_suggestions',
                'ordering': ['-frequency', '-last_used'],
                'indexes': [models.Index(fields=['description'], name='finance_des_descrip_744104_idx'), models.Index(fields=['category'], name='finance_des_categor_c39e4b_idx'), models.Index(fields=['frequency'], name='finance_des_frequen_7e8754_idx')],
            },
        ),
    ]
