# Generated by Django 5.0.7 on 2025-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoicesettlement_settlementpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='shop_margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
