# Generated by Django 5.0.7 on 2025-06-21 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delivery_settlement_date_delivery_settlement_notes_and_more'),
        ('sales', '0003_invoice_shop_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='products.batch'),
        ),
    ]
