# Generated by Django 5.0.7 on 2025-06-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoiceitem_batch'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE invoice_items DROP COLUMN allocated_batches;",
            reverse_sql="ALTER TABLE invoice_items ADD COLUMN allocated_batches jsonb NOT NULL DEFAULT '[]';"
        ),
    ]
