# Generated by Django 5.0.7 on 2025-06-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_invoiceitem_batch'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$ 
            BEGIN 
                IF EXISTS (SELECT column_name FROM information_schema.columns 
                          WHERE table_name='invoice_items' AND column_name='allocated_batches') THEN
                    ALTER TABLE invoice_items DROP COLUMN allocated_batches;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE invoice_items ADD COLUMN allocated_batches jsonb NOT NULL DEFAULT '[]';"
        ),
    ]
