# Generated by Django 5.0.7 on 2025-06-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delivery_settlement_date_delivery_settlement_notes_and_more'),
        ('sales', '0005_auto_20250621_1515'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'product', 'batch')},
        ),
    ]
