# Generated by Django 5.0.7 on 2025-06-11 06:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Grow Aloe Business', max_length=200)),
                ('company_address', models.TextField(default='123 Business Street\nCity, State 12345')),
                ('company_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('company_email', models.EmailField(default='info@growaloe.com', max_length=254)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex color code (e.g., #007bff)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code (e.g., #6c757d)', max_length=7)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers', max_length=10)),
                ('invoice_footer_text', models.TextField(default='Thank you for your business!\nThis is a computer-generated invoice and does not require a signature.', help_text='Footer text to appear on invoices')),
                ('show_logo_on_invoice', models.BooleanField(default=True)),
                ('show_company_details', models.BooleanField(default=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('default_payment_terms', models.TextField(blank=True, help_text='Default payment terms and conditions', null=True)),
                ('default_due_days', models.PositiveIntegerField(default=30, help_text='Default days until payment is due')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
    ]
