# Generated by Django 5.0.7 on 2025-07-11 09:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Grow Aloe Business', max_length=200)),
                ('company_address', models.TextField(default='123 Business Street\nCity, State 12345')),
                ('company_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('company_email', models.EmailField(default='info@growaloe.com', max_length=254)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('company_tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])])),
                ('primary_color', models.CharField(default='#007bff', help_text='Hex color code (e.g., #007bff)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Hex color code (e.g., #6c757d)', max_length=7)),
                ('invoice_prefix', models.CharField(default='INV', help_text='Prefix for invoice numbers', max_length=10)),
                ('invoice_footer_text', models.TextField(default='Thank you for your business!\nThis is a computer-generated invoice and does not require a signature.', help_text='Footer text to appear on invoices')),
                ('show_logo_on_invoice', models.BooleanField(default=True)),
                ('show_company_details', models.BooleanField(default=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('currency_symbol', models.CharField(default='$', max_length=5)),
                ('max_shop_margin_for_salesmen', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Maximum shop margin percentage that salesmen can set (owners have no restrictions)', max_digits=5)),
                ('default_payment_terms', models.TextField(blank=True, help_text='Default payment terms and conditions', null=True)),
                ('default_due_days', models.PositiveIntegerField(default=30, help_text='Default days until payment is due')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_debits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_credits', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoices', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_settlements', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'ordering': ['-end_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('category', models.CharField(choices=[('invoice_settlement', 'Invoice Settlement'), ('cash_sale', 'Cash Sale'), ('other_income', 'Other Income'), ('loan_received', 'Loan Received'), ('capital_injection', 'Capital Injection'), ('refund_received', 'Refund Received'), ('invoice_created', 'Invoice Created'), ('purchase', 'Purchase'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries', 'Salaries'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('office_expenses', 'Office Expenses'), ('agency_payment', 'Agency Payment'), ('loan_payment', 'Loan Payment'), ('tax_payment', 'Tax Payment'), ('bank_charges', 'Bank Charges'), ('other_expense', 'Other Expense')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_id', models.CharField(blank=True, help_text='Invoice ID if related to invoice', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
