# Generated by Django 5.0.7 on 2025-06-18 04:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='max_shop_margin_for_salesmen',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Maximum shop margin percentage that salesmen can set (owners have no restrictions)', max_digits=5),
        ),
    ]
