# Generated by Django 5.0.7 on 2025-06-18 11:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companysettings_max_shop_margin_for_salesmen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invoices', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_settlements', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actual_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Financial Summary',
                'verbose_name_plural': 'Financial Summaries',
                'ordering': ['-end_date'],
                'unique_together': {('start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('category', models.CharField(choices=[('sales_cash', 'Sales - Cash'), ('sales_collection', 'Sales - Collection'), ('other_income', 'Other Income'), ('loan_received', 'Loan Received'), ('capital_injection', 'Capital Injection'), ('purchase', 'Purchase'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('salaries', 'Salaries'), ('transport', 'Transport'), ('marketing', 'Marketing'), ('office_expenses', 'Office Expenses'), ('loan_payment', 'Loan Payment'), ('tax_payment', 'Tax Payment'), ('other_expense', 'Other Expense')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
